### ISSUE TITLE
Problems with Geoserver Community-Plugin / Map-Reduce Ingest of GDELT

### ISSUE THREAD

**Issue by SlowMo24** [geomesa/geomesa-tutorials#17]
Hey dear Geomesa-Community,

unfortunately I don't get accepted to the Geomesa-Users-List. This is why I post my issues here:

The Community-Plug-in for Geoserver is not compilable any more. And there is no ready to use .jar on the web accessible also. I think it needs major revision because most of the dependencies mentioned in the pom.xml are not accessible any more (e.g. geomesa-core-accumulo1.5, geomesa-utils-accumulo1.5 ...). Unfortunately I cannot create a pull-request because I don't know which packages succeed e.g. geomesa-core-accumulo1.5 stated in line 59.

Also line 27 has a simple typo:  `<name>Anthony Fox<name>` needs `</name>` at the end.

I guess this is also why I cannot display the heat-map at the end of the "Map-Reduce Ingest of GDELT"-Tutorial. It only shows me this XML-Error-Message. This might be because the Goserver-Community-Plugin is missing:

```
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE ServiceExceptionReport SYSTEM "[GEOSERVER_ADDRESS]/schemas/wms/1.1.1/WMS_exception_1_1_1.dtd">
<ServiceExceptionReport version="1.1.1" > 
    <ServiceException>
        java.lang.RuntimeException: Unable to find function geomesa:Density
            Unable to find function geomesa:Density
    </ServiceException>
</ServiceExceptionReport>
```

Thank you in advance for your help

Kind regards

Mo

**Comment by elahrvivaz** [comment]
Hi Mo,
Our geoserver community module isn't being very well maintained, as you mentioned. We're in the process of updating and relocation some of that code. However, I think your issue is due to a missing jar. In your geoserver `WEB-INF/lib`, do you have a `geomesa-process-<version>.jar`? If not, try copying that in and see if the heatmap works.

**Comment by SlowMo24** [comment]
Great! You are a problemsolver! I think this should be mentioned in the docs because I could not find this information there.  
Now there is one last issue. I cannot add a raster-datastore to Geoserver. The Data is in Accumulo but when I want to add the raster layer (Accumulo (Geomesa Raster) - Tile imagery in Apache Accumulo™) I only get the option to put an URL as connection parameters. I think this is linked to the question because this should be due to the missing community plug-in. Which .jar do I have to add or how can I tell Geoserver to connect to an Accumulo Datastore? The `geomesa-raster-<version>.jar` is already in `WEB-INF/lib`.

Regards  
Mo

**Comment by elahrvivaz** [comment]
Nice. We've updated the docs about that process jar, but it hasn't gone live yet.
Our geoserver community module is lagging behind at the moment - we've just made public some of the code for connecting to the raster store here: https://github.com/ccri/geomesa-geoserver
It's pointing at version `3.0.0-SNAPSHOT` right now - you will have to modify the pom to point to an earlier geomesa version and possibly fix some imports in the source code, then build and extract the `geomesa-coverage/target/install.tgz` into `geoserver/WEB-INF/lib`.
Thanks,

**Comment by elahrvivaz** [comment]
@SlowMo24 I pointed you to the wrong thing, sorry. The actual UI you need is here: https://github.com/ccri/geoserver/tree/geomesa_community_2.8.x_1.2/src/community/geomesa
I verified that it works with geomesa 1.2.6.
Thanks,

**Comment by mdzimmerman** [comment]
> We've updated the docs about that process jar, but it hasn't gone live yet.

I've updated the 1.2.6 docs, so they should be there now.

**Comment by SlowMo24** [comment]
hm, unfortunately, geoserver won’t start if I put the geomesa-gs-2.8-SNAPSHOT.jar in the WEB-INF/lib folder. There is also no failure log. 
But if you verified, that it works... I’m certainly not depending on it, it was just to test the possibilities.
thanks for your help!
@mdzimmerman  nice update!

**Comment by y0uzha** [comment]
> @SlowMo24 I pointed you to the wrong thing, sorry. The actual UI you need is here: https://github.com/ccri/geoserver/tree/geomesa_community_2.8.x_1.2/src/community/geomesa
I verified that it works with geomesa 1.2.6.
Thanks,

hi, i've try to build this plugin but it stuck at this section 
Downloading: http://www.hibernatespatial.org/repository/org/geotools/gt-referencing/14-SNAPSHOT/maven-metadata.xml
[WARNING] Could not transfer metadata org.geotools:gt-referencing:14-SNAPSHOT/maven-metadata.xml from/to hibspat (http://www.hibernatespatial.org/repository): Connect to www.hibernatespatial.org:80 [www.hibernatespatial.org/62.213.201.148] failed: Connection timed out
[WARNING] Failure to transfer org.geotools:gt-referencing:14-SNAPSHOT/maven-metadata.xml from http://www.hibernatespatial.org/repository was cached in the local repository, resolution will not be reattempted until the update interval of hibspat has elapsed or updates are forced. Original error: Could not transfer metadata org.geotools:gt-referencing:14-SNAPSHOT/maven-metadata.xml from/to hibspat (http://www.hibernatespatial.org/repository): Connect to www.hibernatespatial.org:80 [www.hibernatespatial.org/62.213.201.148] failed: Connection timed out
Downloading: http://www.hibernatespatial.org/repository/org/geotools/library/14-SNAPSHOT/maven-metadata.xml

i think the http://www.hibernatespatial.org was down. any suggestion?

**Comment by elahrvivaz** [comment]
@y0uzha can you try changing the version from 2.8-SNAPSHOT to 2.8.5? I don't believe you should need that hibernatespatial repository

**Comment by y0uzha** [comment]
@elahrvivaz i've try to change the version to 2.8.5 and it was success to build. thx for your help anyway :)

**Comment by jnh5y** [comment]
I think this issue has been addressed.  Feel free to reopen with an updated comment.

**Comment by hardikacs** [comment]
I build plugins geomesa-hbase-gs-plugin result is always the version 1.3.1-m3 and it does not work, how to build to produce versions 1.3.0.0-m3 ?? for using a version 1.3.0.0-m2 also did not work,

**Comment by jnh5y** [comment]
@hardikacs I don't think there is a version 1.3.1-m3 of any of the GeoMesa projects. 

From this page: http://www.geomesa.org/documentation/user/hbase/install.html, you can download the GeoMesa HBase version 1.3.0 distribution bundle.  

This project is separate from GeoMesa, and the version numbers are slightly different.
