### ISSUE TITLE
Update tutorials for GeoMesa 1.2.6

### ISSUE THREAD

**Issue by fosskers** [geomesa/geomesa-tutorials#20]
As GM 1.2.6 is the latest stable version, it would be helpful if the `1.2` branch reflected that.

I'm currently trying to run the tutorials in a [heavily dockerized environment](https://github.com/geodocker/geodocker-accumulo-geomesa) that depends on `1.2.6`.

Thanks guys.

**Comment by elahrvivaz** [comment]
1.2.6.0 tag created and 1.2 branch updated to 1.2.6.1-SNAPSHOT. Let me know if I missed anything.
