### ISSUE TITLE
Error running GeoMesa Tutorial

### ISSUE THREAD

**Issue by cinbau** [geomesa/geomesa-tutorials#25]
I am getting a unsupported major.minor error when trying to run the GeoMesa Quick Start Tutorial
"Exception in thread "main" java.lang.UnsupportedClassVersionError: com/example/geomesa/accumulo/AccumuloQuickStart : Unsupported major.minor version 52.0..."

I have GeoMesa 1.2.6, Accumulo 1.7.2, ZooKeeper 3.4.9, and Hadoop 2.7.3 running.  Today, I followed the instructions on http://www.geomesa.org/documentation/tutorials/geomesa-quickstart-accumulo.html for the quick start tutorial.  I edited the pom.xml with the correct versions.   

I think the problem is that the "git clone https://github.com/geomesa/geomesa-tutorials.git" is pulling the geomesa-quickstart-accumulo-1.3.0.0-m2-SNAPSHOT.jar and I am running 1.2.6

**Comment by elahrvivaz** [comment]
you can check out the appropriate tag after cloning the tutorial - it's `geomesa-tutorials-1.2.6.0`. Can you see if that works? You might just need to update your java version - I believe 1.2.6 requires java 8.

**Comment by cinbau** [comment]
Thanks for your quick response and the full tag name.  I checked out the proper tag and re-built the tutorial.  I still got the error, but it was because I was pointing to the wrong version of java on the VM.   I ran the geomesa tutorial jar again with the correct JDK8 and it worked.

**Comment by elahrvivaz** [comment]
great. I've added a ticket to mention tags in our tutorial instructions in the geomesa jira here: https://geomesa.atlassian.net/browse/GEOMESA-1525. Thanks,
