### ISSUE TITLE
where is the API doc ?

### ISSUE THREAD

**Issue by zhouhoo** [geomesa/geomesa-tutorials#35]
Geomesa is a great tool,  and the example is helpful to start ,but  I can not find the API doc.  I really want to look up functions declaration and  some more information especially to fix bugs.

**Comment by elahrvivaz** [comment]
We don't publish API docs - we conform to the geotools API. GeoMesa-specific configurations, etc are available in our docs (http://www.geomesa.org/documentation/) and the source code is on github (https://github.com/locationtech/geomesa)
