### ISSUE TITLE
How to build a line example using geomesa Hbase

### ISSUE THREAD

**Issue by gongenbo** [geomesa/geomesa-tutorials#37]
I find this tutorials only has example to bulid point type data,and how can I use geomesa hbase buid trace data or line type data? Are there has example?

**Comment by elahrvivaz** [comment]
For this example, you could modify the geometry type to be a LineString here:

Then modify the geometries you're setting to be linestrings here:

https://github.com/geomesa/geomesa-tutorials/blob/master/geomesa-quickstart-hbase/src/main/java/com/example/geomesa/hbase/HBaseQuickStart.java#L133
