### ISSUE TITLE
Using idea compile hbase quick start prompt Missing required option: bigtable_table_name

### ISSUE THREAD

**Issue by gongenbo** [geomesa/geomesa-tutorials#38]
when I use idea compile hbase quick start project,It 's a error that Exception in thread "main" org.apache.commons.cli.MissingOptionException: Missing required option: bigtable_table_name.
but I had add this argument,how to resolve it?
![qq 20170323113402](https://cloud.githubusercontent.com/assets/7285943/24231045/3ba5a58c-0fbd-11e7-9679-133219ca5c6f.jpg)

**Comment by elahrvivaz** [comment]
If you look at 'running the tutorial', you will see the arguments needed to be passed into the program:
https://github.com/geomesa/geomesa-tutorials/tree/master/geomesa-quickstart-hbase#running-the-tutorial.
Thanks,
