### ISSUE TITLE
GeoMesa Accumulo tutorial: There are no tablet servers

### ISSUE THREAD

**Issue by ianmcderp** [geomesa/geomesa-tutorials#39]
I tried to run the `geomesa-quickstart-accumulo` tutorial, managed to build the maven artifacts and ran the tutorial with the following command:

`
java -cp geomesa-quickstart-accumulo/target/geomesa-quickstart-accumulo-${geomesa.version}.jar
com.example.geomesa.accumulo.AccumuloQuickStart
-instanceId instance
-zookeepers localhost:2181
-user leader
-password leader
-tableName test1
`

I then got the following result from the command line:

`There are no tablet servers: check that zookeeper and accumulo are running.`

Accumulo treats this info as `WARN` - why does this affect the tutorial? How can I fix this issue?
Additionally: I assumed that the required user is leader/leader - is there any way to create this user from scratch?

**Comment by elahrvivaz** [comment]
I don't think that warning is killing it. Did you install or set up a local accumulo instance (you appear to be pointing to a local instance)? The credentials will be whatever you defined them to be in accumulo.
Note that this tutorial requires a pre-existing accumulo instance to connect to. You can create users through the accumulo shell - refer to the accumulo documentation for details.

**Comment by ianmcderp** [comment]
It turned out that I haven't waited long enough until Accumulo was ready to process requests - credentials were (luckily) correct! Thanks for your support though, @elahrvivaz!
