### ISSUE TITLE
geomesa-hbase-datastore's class DataStore return null and i got a NullPointException

### ISSUE THREAD

**Issue by gongenbo** [geomesa/geomesa-tutorials#40]
When I use the geomesa-quickstart-hbase example,It works very well,but when I transform the project to a java web project and call the queryFeatures method  used a servlet doGet method, It has an error that the DataStore return null,and dataStore.createSchema(simpleFeatureType) method return a nullpointException.
please help me,thanks a lot.

![Uploading 未标题-1.jpg…]()

**Comment by gongenbo** [comment]
![image](https://cloud.githubusercontent.com/assets/7285943/24327805/c9cf9efc-120c-11e7-9570-fa8e4e0e380a.png)

**Comment by elahrvivaz** [comment]
This isn't really the correct place for problems like this - going to close. I see you also emailed the user list, and replied to you there.
Issues against the github repo should involve actual problems or enhancements to the repo code.
Thanks,
Emilio
