### ISSUE TITLE
geomesa-quickstart-accumulo: exception while doing multi-scan

### ISSUE THREAD

**Issue by taco64** [geomesa/geomesa-tutorials#41]
I tried the tutorial geomesa-quickstart-accumulo but the 1st query (queryFeatures) throws the exception. Subsequent queries (secondaryIndexExample) are successfully processed and printed the result.

Any suggestions to solve the issue?

My emvironemnt is:  accumulo 1.6.1, hadoop 2.4.1, zookeeper 3.4.6, OpenJDK 1.8.0_121, geomesa-accumulo-distributed-runtime-1.3.0-20170318.042847-194.jar
Tutorial version is:  1.3.1.0-SNAPSHOT

Logs:  [clientlog.txt](https://github.com/geomesa/geomesa-tutorials/files/871743/clientlog.txt), [serverlog.txt](https://github.com/geomesa/geomesa-tutorials/files/871744/serverlog.txt)

**Comment by elahrvivaz** [comment]
You should update your distributed-runtime jar to 1.3.1, if you haven't modified the quickstart pom. It uses geomesa-1.3.1:
https://github.com/geomesa/geomesa-tutorials/blob/master/pom.xml#L34

**Comment by taco64** [comment]
I tried to update distributed-runtime jar to 1.3.1 and also modified the quickstart pom to 1.3.0 and rebuild the tutorial. But they did not work either.

(1) Update distributed-runtime jar
- Replace the distributed-runtime to geomesa-accumulo-distributed-runtime_2.11-1.3.1.jar
- Queries are all failed.
- Message is: "exception while scanning tablet k;AccumuloQuickStart\~stats-count;AccumuloQuickStart~stats-bounds"

Logs:  [clientlog-1.txt](https://github.com/geomesa/geomesa-tutorials/files/874507/clientlog-1.txt), [serverlog-1.txt](https://github.com/geomesa/geomesa-tutorials/files/874508/serverlog-1.txt)

(2) Modify the quickstart pom to 1.3.0 and rebuild (distributed-runtime is 1.3.0)
- Changed the version as "<geomesa.version>1.3.0</geomesa.version>"
- Rebuild the tutorial with the command: "mvn clean install -pl geomesa-quickstart-accumulo"
- 1st query throws the exception but others are processed. It's same as the original post.
- Message is: "exception while doing multi-scan"

Logs:  [clientlog-2.txt](https://github.com/geomesa/geomesa-tutorials/files/874509/clientlog-2.txt), [serverlog-2.txt](https://github.com/geomesa/geomesa-tutorials/files/874510/serverlog-2.txt)

What could be wrong with my environment?

**Comment by elahrvivaz** [comment]
for the 1.3.1 jar, you need to update the version of commons-vfs in accumulo. See the first warning here: http://www.geomesa.org/documentation/user/accumulo/install.html#installing-the-accumulo-distributed-runtime-library

**Comment by taco64** [comment]
I updated the jar file to commons-vfs2-2.1.jar in accumulo. But the result is same ("exception while doing multi-scan").

Logs: [clientlog.txt](https://github.com/geomesa/geomesa-tutorials/files/875884/clientlog.txt), [serverlog.txt](https://github.com/geomesa/geomesa-tutorials/files/875885/serverlog.txt)

Any other suggestions?

**Comment by elahrvivaz** [comment]
Updating the jar fixed the classloading issue, but now you're back to the `input string null` exceptions, which indicate a mismatch between the iterator version (distributed-runtime jar) and the client version. I would double check once again that your versions are all 1.3.1. I assume you're using hdfs classloading for the distributed runtime jar? Also check that there aren't any geomesa jars in `accumulo/lib` or `accumulo/lib/ext`, as those will take precedence over jars in hdfs.

**Comment by taco64** [comment]
I double checked the iterator and client version then found geomesa.version in quickstart pom was still 1.3.0. There is still an exception thrown but three queries are processed successfully after built the client again. Thanks for your help! And I'm not using hdfs classloading anyway.

Is it OK to ignore the client exception "java.io.IOException: The stream is closed"? Or should I do something to fix it?

Logs:  [clientlog.txt](https://github.com/geomesa/geomesa-tutorials/files/877746/clientlog.txt), [libs.txt](https://github.com/geomesa/geomesa-tutorials/files/877747/libs.txt)

**Comment by elahrvivaz** [comment]
nice, good to hear. In normal operation you shouldn't get the IOExceptions - usually you see those if a client disconnects while it's reading data from accumulo. It could also just be normal accumulo connection management, but if it happens every time you run that seems odd.

**Comment by taco64** [comment]
I see this exception every time I try the tutorial. Whole system is running on VM with slow PC now, so I will try again with faster Linux box. Anyway, this is not a topic of this issue so closed the log.
