### ISSUE TITLE
GeoMesa Accumulo data store not available in GeoServer

### ISSUE THREAD

**Issue by ianmcderp** [geomesa/geomesa-tutorials#42]
I tried to run the quickstart tutorial for GeoMesa Accumulo in GeoServer from [the GeoMesa website](http://www.geomesa.org/documentation/tutorials/geomesa-quickstart-accumulo.html) - I managed to get GeoMesa Accumulo up and running, but I can't get the GeoMesa Accumulo datastore to be shown in GeoServer as a store.

I ran the steps as described [in the tutorial](http://www.geomesa.org/documentation/user/accumulo/install.html#install-accumulo-geoserver), using GeoServer (with WPS plugin) v2.11.0 running in a Tomcat container v7.1. I then built the latest version of the [GeoMesa master from GitHub](https://github.com/locationtech/geomesa/tree/master/geomesa-accumulo/geomesa-accumulo-gs-plugin) and put the JARs from `geomesa-$VERSION/geomesa-accumulo/geomesa-accumulo-gs-plugin/target/` to GeoServer's lib directory. I also put the mentioned JARs for Accumulo v1.7.2 and Hadoop v2.7.2 to the GeoServer lib directory too:

- accumulo-core-1.7.2.jar
- accumulo-fate-1.7.2.jar
- accumulo-server-base-1.7.2.jar
- accumulo-trace-1.7.2.jar
- accumulo-start-1.7.2.jar
- libthrift-0.9.1.jar
- zookeeper-3.4.6.jar
- htrace-core-3.1.0-incubating.jar
- commons-vfs2-2.1.jar
- commons-configuration-1.6.jar
- hadoop-auth-2.7.2.jar
- hadoop-client-2.7.2.jar
- hadoop-common-2.7.2.jar
- hadoop-hdfs-2.7.2.jar

We then restarted GeoServer and inspected the logs: we couldn't find any errors or warnings in both Catalina logs and localhost logs. GeoServer seems to be up and running, WPS plugin is shown on the front page, but when we go to Stores > Add new store, we don't get Accumulo data store as an option.

Is there any version (in)compatibility that I have to know about?

FYI: we are running GeoMesa Accumulo from a Docker image that you can find [here](https://github.com/jamesmcclain/GeoMesaDocker).

**Comment by elahrvivaz** [comment]
Couldn't quite tell from your post, but you extracted the tar.gz from geomesa-accumulo-gs-plugin?
We're currently targeting geotools 15/geoserver 2.9. I'm not sure if anyone has deployed to 2.11 yet. Sometimes minor issues crop up when bumping geoserver versions. You might try changing the root geomesa pom `<gt.version>15.1</gt.version>` to match the version deployed with geoserver 2.11 (which I believe is 16.2). If there are failing tests, then that is a red flag.

**Comment by elahrvivaz** [comment]
GeoServer tends to bury exceptions that occur when loading data stores - you might be able to see the issue if you remote debug your instance during startup and put a breakpoint in `DataStoreFinder.getAvailableDataStores`

**Comment by ianmcderp** [comment]
> We're currently targeting geotools 15/geoserver 2.9. I'm not sure if anyone has deployed to 2.11 yet
I also tried to get it running with the same setup as above, but with GeoServer v2.9 instead - it didn't work.

> You might try changing the root geomesa pom <gt.version>15.1</gt.version>
I will dig into that, maybe changing the version here helps.

Thanks for your rapid response, I'll keep you posted!

**Comment by jnh5y** [comment]
@ianmcderp did you have any more luck on this issue?

**Comment by ianmcderp** [comment]
@jnh5y: unfortunately, I have not.

> You might try changing the root geomesa pom <gt.version>15.1</gt.version>

I tried it one more time with Geotools v15 and GeoServer 2.9.x, but I could not get it running, it's still not available in the GeoServer store selection.

> I also put the mentioned JARs for Accumulo v1.7.2 and Hadoop v2.7.2 to the GeoServer lib directory

This time, I used the mentioned JARs straight from my running Accumulo and Hadoop instances - I couldn't get it running though, same result as above.

I haven't tried to debug GeoServer on startup yet, but I guess it seems to be the last resort. I'll keep you posted if I can find something valuable from this session.

I still hope that someone has a similar setup as I do and can provide a list of used dependencies, because I find the provided list at the Geomesa tutorials page to be described vaguely and leaves too much space for blind guessing when it comes to a JARs version number.

**Comment by elahrvivaz** [comment]
we have some scripts to download dependencies for you - in general we don't specify exact versions because people's setups vary. In the geomesa-accumulo-dist bundle, there is a script called `install-hadoop-accumulo.sh` that will download a known working set of jars. You could try that in a fresh geoserver install. The exact jar versions don't usually have to match your environment, likely the script would work as is (it targets accumulo 1.7 and hadoop 2.4)

**Comment by jnh5y** [comment]
@ianmcderp Any more luck here?

**Comment by ianmcderp** [comment]
@jnh5y I haven't had time to investigate @elahrvivaz's suggestion on the `install-hadoop-accumulo.sh` unfortunately. I'm also sorry to say that my team and I don't have any more time to look into this 'issue' as we found another solution in the meanwhile. Thank you both @jnh5y  and @elahrvivaz for your support and input, we really appreciated any helping hand on this topic! 👍

**Comment by jnh5y** [comment]
@ianmcderp sounds great.  I'm going to close this issue for the moment.  Good luck!  Also, don't forget about Gitter!
