### ISSUE TITLE
Different versions of Apache Curator in accumulo quickstart

### ISSUE THREAD

**Issue by elahrvivaz** [geomesa/geomesa-tutorials#5]
Looks like a mix of 2.6.0 and 2.7.1 are getting into the accumulo quickstart shaded jar, causing exceptions to be thrown when creating a new schema. Should only be 2.7.1 present.

**Comment by elahrvivaz** [comment]
I can't reproduce this in either master or the 1.2.1 tag.

**Comment by elahrvivaz** [comment]
The error was coming from changing the hadoop version to 2.6.4. We should probably explicitly set the curator version in the pom so that hadoop version doesn't affect it.

**Comment by darcular** [comment]
Same problem here. It works after I exclude curator-client from hadoop-common in its pom.xml.

**Comment by aheyne** [comment]
This should be fixed in #29
