### ISSUE TITLE
Couldn`t find type "DataFrame"

### ISSUE THREAD

**Issue by Asgoret** [geomesa/geomesa-tutorials#50]
Hi to everyone. 
I`m nooby in geomesa, so start from making examples and tutorials. 
In "Geomesa Spark with Zeppelin" I have strange error when enter:
_%spark
def printDF(df: DataFrame) = {
  val dfc = df.collect
  println("%table")
  println(df.columns.mkString("\t"))
  dfc.foreach(r => println(r.mkString("\t")))
}_
And error:
_<console>:25: error: not found: type DataFrame
       def printDF(df: DataFrame) = {_
Someone have this error?

My system:
OS: Centos 7.2
Zeppelin: 0.7.2
Hadoop: Hortonworks Data Platform 2.6.1 was installed via Ambari install.
Spark: 2.1.1.2.6.1.0-129
Geomesa: Geomesa Accumulo 2.11-1.3.3 build from source 

UPD#1:
If I change "DataFrame" to on of my tables in accumulo, i get same error.
_:25: error: not found: type geonames
def printDF(df: geonames) = {_

geonames - table name in geomesa accumulo.

UPD#2:
I can run "Hello World" from Spark [tutorials ](https://spark.apache.org/docs/1.2.0/quick-start.html)and get correct answer.
_%spark
val textFile = sc.textFile("README.md")
textFile: org.apache.spark.rdd.RDD[String] = README.md MapPartitionsRDD[1] at textFile at <console>:27_

And can go to "Spark UI" from Zeppelin interpretators.

P.S. Sorry for mistakes, english is foreign language for me.

**Comment by Asgoret** [comment]
UPD:
If I change "DataFrame" to on of my tables in accumulo, i get same error. 
_<console>:25: error: not found: type geonames
       def printDF(df: geonames) = {_

geonames - table name in geomesa accumulo.

**Comment by elahrvivaz** [comment]
I believe that you need to import the class:
`import org.apache.spark.sql.DataFrame`

**Comment by Asgoret** [comment]
@elahrvivaz Thanks. You`ve right.  Strange that some of libraries isn`t in zeppelin. 

Not issue, but question. You know how get describe\scan of table vie spark in zeppelin? Changing "%table" isn`t work. I have this output on all of my attempts:
_import org.apache.spark.sql.DataFrame
printDF: (df: org.apache.spark.sql.DataFrame)Unit_

**Comment by elahrvivaz** [comment]
I believe you'd have to load some data, then register it as a temp table as described here:
http://www.geomesa.org/documentation/current/user/spark/sparksql.html#example

**Comment by Asgoret** [comment]
@elahrvivaz  Thanks, will read doc. Please, close issue.

**Comment by elahrvivaz** [comment]
sure, feel free to jump into our gitter channel for help: https://gitter.im/locationtech/geomesa
