### ISSUE TITLE
geomesa-examples-gdelt-1.3.3.0.jar could not run

### ISSUE THREAD

**Issue by xqx930807** [geomesa/geomesa-tutorials#54]
xqx@xqx-Wenxiang-E620:~/bigdata/geomesa-tutorials$ hadoop jar geomesa-examples-gdelt/target/geomesa-examples-gdelt-1.3.3.0.jar \ com.example.geomesa.gdelt.GDELTIngest            \
     -instanceId GeoAcc               \
     -zookeepers localhost:2181             \
     -user root -password ***          \
    -tableName myNamespace.gdelt -featureName event              \
     -ingestFile hdfs:///gdelt/uncompressed/gdelt2017.tsv
Exception in thread "main" java.lang.ClassNotFoundException:  com.example.geomesa.gdelt.GDELTIngest
    at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:348)
    at org.apache.hadoop.util.RunJar.run(RunJar.java:214)
    at org.apache.hadoop.util.RunJar.main(RunJar.java:136)

**Comment by xqx930807** [comment]
PS:
I cloned the code and checkout the tag geomesa-tutorials-1.3.3.0,changed the pom.xml and complied successfully.
my dev environment is on hadoop 2.6.4 zookeeper 3.4.6 accumulo 1.7.2.

**Comment by xqx930807** [comment]
Sorry I have found the cause.
It is caused by "\".Please delete it from shell commands.
So pay attention to the SHELL command when using hadoop,accumulo and geomesa.

**Comment by elahrvivaz** [comment]
thanks for finding this. which shell command had the issue? I don't see any quotes in the command you ran.

**Comment by xqx930807** [comment]
@elahrvivaz 
My Shell command is `xqx@xqx-Wenxiang-E620:~/bigdata/geomesa-tutorials$ hadoop jar geomesa-examples-gdelt/target/geomesa-examples-gdelt-1.3.3.0.jar \ com.example.geomesa.gdelt.GDELTIngest 
-instanceId GeoAcc 
-zookeepers localhost:2181 
-user root -password *** 
-tableName myNamespace.gdelt -featureName event 
-ingestFile hdfs:///gdelt/uncompressed/gdelt2017.tsv`

the `\` symbol between JAR name and  class name should be removed.
