### ISSUE TITLE
Is GeoMesa 1.3.x compatible with Spark 2.1?

### ISSUE THREAD

**Issue by xqx930807** [geomesa/geomesa-tutorials#55]
Now I am working with the Hortonworks HDP Hadoop Platform.
The Spark version is 2.1.0.
I found the spark version in the pomx.xml of geomesa or geomesa-tutorials is 2.0.0.
Is GeoMesa 1.3.x compatible with Spark 2.1?

**Comment by elahrvivaz** [comment]
I believe that it is compatible - spark is a 'provided' dependency in GeoMesa, so we don't bundle it directly. If you try it and run into any issues, please let us know.
