### ISSUE TITLE
Problem with setting up Geomesa, maven

### ISSUE THREAD

**Issue by alicjusz23** [geomesa/geomesa-tutorials#56]
Hello,

I have a problem while running: 
mvn clean install -pl geomesa-quickstart-accumulo
Here are error logs:

[INFO] Scanning for projects...
Downloading: https://repo.locationtech.org/content/groups/snapshots/org/locationtech/geomesa/geomesa_2.11/1.4.0-SNAPSHOT/geomesa_2.11-1.4.0-20180108.144710-128.pom
Jan 09, 2018 3:43:20 PM org.apache.maven.wagon.providers.http.httpclient.impl.client.DefaultHttpClient tryExecute
INFO: I/O exception (java.net.SocketException) caught when processing request: Connection reset
Jan 09, 2018 3:43:20 PM org.apache.maven.wagon.providers.http.httpclient.impl.client.DefaultHttpClient tryExecute
INFO: Retrying request
Jan 09, 2018 3:43:41 PM org.apache.maven.wagon.providers.http.httpclient.impl.client.DefaultHttpClient tryExecute
INFO: I/O exception (java.net.SocketException) caught when processing request: Connection reset
Jan 09, 2018 3:43:41 PM org.apache.maven.wagon.providers.http.httpclient.impl.client.DefaultHttpClient tryExecute
INFO: Retrying request
Jan 09, 2018 3:44:02 PM org.apache.maven.wagon.providers.http.httpclient.impl.client.DefaultHttpClient tryExecute
INFO: I/O exception (java.net.SocketException) caught when processing request: Connection reset
Jan 09, 2018 3:44:02 PM org.apache.maven.wagon.providers.http.httpclient.impl.client.DefaultHttpClient tryExecute
INFO: Retrying request
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project com.example.geomesa:geomesa-tutorials:1.4.0.0-SNAPSHOT (/home/ala/Install/geomesa-tutorials/pom.xml) has 1 error
[ERROR]     Non-resolvable import POM org.locationtech.geomesa:geomesa_2.11:1.4.0-SNAPSHOT: Could not transfer artifact org.locationtech.geomesa:geomesa_2.11:pom:1.4.0-20180108.144710-128 from/to locationtech-snapshots (https://repo.locationtech.org/content/groups/snapshots): Connection reset @ line 59, column 25 -> [Help 2]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException

I've also changed <enable> to true by snapshot tags in 289 line in pom file but it desn't help.
It seems maven can't find pom files at repo.locationtech.org but they are there.
Could you give me any suggestions how to solve this problem?

**Comment by elahrvivaz** [comment]
are you able to download the file from that path (https://repo.locationtech.org/content/groups/snapshots/org/locationtech/geomesa/geomesa_2.11/1.4.0-SNAPSHOT/geomesa_2.11-1.4.0-20180108.144710-128.pom), outside of maven?

**Comment by alicjusz23** [comment]
yes, I am

**Comment by elahrvivaz** [comment]
you can always build geomesa locally, instead of pulling it from the repository. Follow the instructions here to install into your local cache: https://github.com/locationtech/geomesa#building-from-source
note that maven will be default check for newer snapshot versions after 24 hours - you can disable this by running in offline mode (`-o`)

**Comment by alicjusz23** [comment]
Unfortunately there is another trouble:
[ERROR] Failed to execute goal com.mycila:license-maven-plugin:2.10:check (license-check) on project geomesa_2.11: Execution license-check of goal com.mycila:license-maven-plugin:2.10:check failed: Plugin com.mycila:license-maven-plugin:2.10 or one of its dependencies could not be resolved: Could not transfer artifact org.apache.maven.wagon:wagon-provider-api:jar:1.0-beta-4 from/to central (https://repo.maven.apache.org/maven2): Connection reset -> [Help 1]
[Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginResolutionException

**Comment by elahrvivaz** [comment]
hmm, there seems to be something wrong with your maven install or environment. are you able to build other projects?
