### ISSUE TITLE
Support geomesa in R

### ISSUE THREAD

**Issue by harryprince** [geomesa/geomesa-tutorials#65]
Many R developers/analysts are using `sf`/`PostGIS` to process spatial data locally,  is it anyone seeking bring geomesa to more sparklyr users to support sparksql query?

# https://github.com/rstudio/sparklyr/issues/1475

**Comment by elahrvivaz** [comment]
I don't know of anyone currently working on it, but if someone wants to do so I think it's a great idea. You could try emailing the [user](https://locationtech.org/mhonarc/lists/geomesa-users/) or [developer](https://locationtech.org/mhonarc/lists/geomesa-dev/) lists, or posting in our [gitter](https://gitter.im/locationtech/geomesa) channel to gauge interest.

**Comment by jnh5y** [comment]
I believe @mdzimmerman showed me GeoMesa RDDs or DFs working with SparkR using Zeppelin.  If I recall, he was able to switch back and forth between using SparkSQL and SparkR.

**Comment by elahrvivaz** [comment]
@harryprince would this be something that would be implemented on the geomesa side, or the sparklyr side?

**Comment by harryprince** [comment]
@elahrvivaz create a sperate project is a better choice, and Sparklyr has a extension mechanism, just like this: https://github.com/rstudio/graphframes. The key point is combine the `sf` to  `sparklyr` and leverage geomesa power. `sf` in R is local version, which is very similar what geomesa does on the cluster.

* https://spark.rstudio.com/extensions/

**Comment by elahrvivaz** [comment]
If this is still an issue, please file a bug in JIRA or start a discussion on the user list or gitter. See https://github.com/locationtech/geomesa#join-the-community
Thanks,
