### ISSUE TITLE
Goemesa Kafka Tutorial:requirement failed: Invalid version/length (expected 1-10): 2-5

### ISSUE THREAD

**Issue by youngHello** [geomesa/geomesa-tutorials#68]
Hello,

I have encountered a problem while running  java -cp geomesa-tutorials-kafka-quickstart-2.1.0-SNAPSHOT.jar org.geomesa.example.kafka.KafkaQuickStart etc, :
28 Sep 18:00:11 WARN [data.KafkaCacheLoader$KafkaCacheLoaderImpl] - Consumer [0] error receiving message from topic geomesa-ds-kafka-tdrive-quickstart:
java.lang.IllegalArgumentException: requirement failed: Invalid version/length (expected 1-10): 2-5
	at scala.Predef$.require(Predef.scala:219)
	at org.locationtech.geomesa.kafka.utils.GeoMessageSerializer.deserialize(GeoMessageSerializer.scala:139)
	at org.locationtech.geomesa.kafka.data.KafkaCacheLoader$KafkaCacheLoaderImpl.consume(KafkaCacheLoader.scala:116)
	at org.locationtech.geomesa.kafka.consumer.ThreadedConsumer$ConsumerRunnable.run(ThreadedConsumer.scala:81)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

so,I can't visualize Data With GeoServer 2.12.x
I am new to Kafka and Geomesa and I cannot google out any solution. 
That's why I come here for help.

**Comment by elahrvivaz** [comment]
Hello,
Can you try checking out the latest stable tag (geomesa-tutorials-2.0.2), rebuilding, and re-running the quickstart?
Thanks,

**Comment by elahrvivaz** [comment]
You may get warnings about invalid messages if there is existing data in the kafka topic, but it should continue running unless it hits 300 consecutive invalid messages - if that is the case, you may need to delete the topic in kafka, or at least delete any messages that are on the topic.

**Comment by youngHello** [comment]
> Hello,
> Can you try checking out the latest stable tag (geomesa-tutorials-2.0.2), rebuilding, and re-running the quickstart?
> Thanks
hi,
After rebuilding geomesa-tutorials-2.0.1, an error tips that
 Error: Could not find or load main class org.geomesa.example.kafka.KafkaQuickStart  when I was running

**Comment by youngHello** [comment]
> You may get warnings about invalid messages if there is existing data in the kafka topic, but it should continue running unless it hits 300 consecutive invalid messages - if that is the case, you may need to delete the topic in kafka, or at least delete any messages that are on the topic.

Hello, 
I recreate the topic geomesa-ds-kafka-tdrive-quickstart in kafka. Although no above error, some logs still show Warn & Info:
Generating test data

WARN  org.locationtech.geomesa.kafka.data.KafkaCacheLoader$KafkaCacheLoaderImpl: This version of Kafka doesn't support timestamps, using system time
INFO  org.locationtech.geomesa.kafka.data.KafkaDataStore: Kafka consumers disabled for this data store instance
Feature type created - register the layer 'tdrive-quickstart' in geoserver with bounds: MinX[116.22366] MinY[39.72925] MaxX[116.58804] MaxY[40.09298]
Press <enter> to continue

However, I  can't visualize data with GeoServer 2.12.x still.
When I run kafka tutorial again, the error shows repeatly

thanks for your reply.

**Comment by elahrvivaz** [comment]
Are the errors showing up in the quickstart console or in geoserver?

**Comment by youngHello** [comment]
The errors showing in geoserver

**Comment by elahrvivaz** [comment]
I'm not sure what the issue is - I ran through the tutorial back when releasing 2.0.2, and it worked ok for me. I'll go through it again before 2.1.0 is released, maybe something has broken in the meantime. The 2.0.2 tag should work though.

**Comment by surajkb74** [comment]
I'm also getting the same error as stated by YoungHello .
then I tried with 2.0.2 release and don't see any error message on geoserver log.

But I'm not seeing any points on geoserver layer view.
Do i need to do something special?

**GeoServer Version
2.12.5**

**Below is the command I executed** 
 geomesa-tutorials-geomesa-tutorials-2.0.2]java -cp geomesa-tutorials-kafka/geomesa-tutorials-kafka-quickstart/target/geomesa-tutorials-kafka-quickstart-2.0.2.jar org.geomesa.example.kafka.KafkaQuickStart --kafka.brokers localhost:9093,localhost:9094,localhost:9095 --kafka.zookeepers localhost:2181 --cleanup
Loading datastore

Loading datastore

Creating schema: taxiId:String,dtg:Date,geom:Point
WARN  org.locationtech.geomesa.kafka.data.KafkaDataStore: Topic [geomesa-ds-kafka-tdrive-quickstart] already exists - it may contain stale data

Generating test data

INFO  org.locationtech.geomesa.kafka.data.KafkaDataStore: Kafka consumers disabled for this data store instance
Feature type created - register the layer 'tdrive-quickstart' in geoserver with bounds: MinX[116.22366] MinY[39.72925] MaxX[116.58804] MaxY[40.09298]
Press <enter> to continue

Writing features to Kafka... refresh GeoServer layer preview to see changes
Current consumer state:
1277=1277|2008-02-03T04:44:04.000Z|POINT (116.3645 39.87738)
Current consumer state:_


**Below is the log from Geoserver and it's look good.**
_2018-10-20 18:14:32,731 INFO [geoserver.wms] - 
Request: getMap
	Angle = 0.0
	BaseUrl = http://hqi1v-biagpm01.drivecaminc.loc:9994/geoserver/
	Bbox = SRSEnvelope[116.22366 : 116.58804, 39.72925 : 40.09298]
	BgColor = java.awt.Color[r=255,g=255,b=255]
	Buffer = 0
	CQLFilter = null
	Crs = GEOGCS["WGS 84", 
  DATUM["World Geodetic System 1984", 
    SPHEROID["WGS 84", 6378137.0, 298.257223563, AUTHORITY["EPSG","7030"]], 
    AUTHORITY["EPSG","6326"]], 
  PRIMEM["Greenwich", 0.0, AUTHORITY["EPSG","8901"]], 
  UNIT["degree", 0.017453292519943295], 
  AXIS["Geodetic longitude", EAST], 
  AXIS["Geodetic latitude", NORTH], 
  AUTHORITY["EPSG","4326"]]
	Elevation = []
	Env = {}
	Exceptions = SE_XML
	FeatureId = null
	FeatureVersion = null
	Filter = null
	Filters = null
	Format = image/jpeg
	FormatOptions = {}
	Get = true
	Height = 766
	Interpolations = []
	Layers = [org.geoserver.wms.MapLayerInfo@e92ef48a]
	MaxFeatures = null
	Palette = null
	RawKvp = {REQUEST=GetMap, SRS=EPSG:4326, FORMAT=image/jpeg, BBOX=116.22366,39.72925,116.58804,40.09298, VERSION=1.1.0, STYLES=, SERVICE=WMS, WIDTH=768, HEIGHT=766, LAYERS=trackpoint:tdrive-quickstart}
	RemoteOwsType = null
	RemoteOwsURL = null
	Request = GetMap
	RequestCharset = UTF-8
	ScaleMethod = null
	Sld = null
	SldBody = null
	SldVersion = null
	SortBy = null
	SortByArrays = null
	SRS = EPSG:4326
	StartIndex = null
	StyleBody = null
	StyleFormat = sld
	Styles = [StyleImpl[ name=point]]
	StyleUrl = null
	StyleVersion = null
	Tiled = false
	TilesOrigin = null
	Time = []
	Transparent = false
	ValidateSchema = false
	Version = 1.1.0
	ViewParams = null
	Width = 768_

**Comment by elahrvivaz** [comment]
@youngHello @surajkb74 what versions of kafka are you using? I will try to re-create the issue you're seeing.

**Comment by surajkb74** [comment]
I'm using 2.11-1.0.0 version .. 
Kafka version : 1.0.0
Scala : 2.11

**Comment by youngHello** [comment]
I'm using 2.11-0.9.0.1 version ..
Kafka version : 0.9.0.1
Scala : 2.11

I found source codes throw exception:
`def deserialize(key: Array[Byte], value: Array[Byte]): GeoMessage = {
    require(key != null && key.length > 0, s"Invalid empty message key")

    **val buffer = ByteBuffer.wrap(key)
    val version = buffer.get()**

    **require(version == 1 && key.length == 10, s"Invalid version/length (expected 1-10): $version-${key.length}")**

    val msgType = buffer.get()
    val ts = Instant.ofEpochMilli(buffer.getLong)`

so, the key of data is not suitable for require code

**Comment by surajkb74** [comment]
@elahrvivaz:  why the points are not showing in the layer when I am using 2.0.2 ? Do you have sample code to test it from curl or wfs request?

**Comment by elahrvivaz** [comment]
@surajkb74 @youngHello I've run through the tutorial again and it's working as expected; I'm not seen any of the errors you're describing. I'm not sure what else to suggest to you, but I think there must be something wrong with your setup.

**Comment by elahrvivaz** [comment]
@surajkb74 you said in gitter that using the same version of geomesa across all your components fixed your issue. @youngHello are you still having problems? Can you ensure that you have the same (non-snapshot) version installed in each component?

**Comment by surajkb74** [comment]
@elahrvivaz : yes ..you are correct.. I made all version to 2.0.2  and then it worked.. I need to test with latest release version 2.1.0
