### ISSUE TITLE
org.geomesa.example.data.TDriveData can not be found in the project

### ISSUE THREAD

**Issue by CzyerChen** [geomesa/geomesa-tutorials#71]
I had learned from the websitr 'https://www.geomesa.org/documentation/tutorials/geomesa-quickstart-kafka.html'. As shown, if I want to run the demo with a small subset of taxi data which is provided ,I have to map the data to entity. The tutorial shows that the code for parsing the data into GeoTools SimpleFeatures is contained in org.geomesa.example.data.TDriveData , but I do not find those. I wonder whether the code included or not.

**Comment by elahrvivaz** [comment]
It's right here: https://github.com/geomesa/geomesa-tutorials/blob/master/geomesa-tutorials-common/src/main/java/org/geomesa/example/data/TDriveData.java#L69
By the way, you can search in github by hitting '\t' (backward slash, then t) and typing the name of the file you want (in this case, TDriveData).
Thanks,
