### ISSUE TITLE
hbase query 

### ISSUE THREAD

**Issue by FjHe** [geomesa/geomesa-tutorials#76]
can't query with projection down to a few attributes  &&  attribute query on a secondary index with a projection

i use hbase 1.2.3

**Comment by FjHe** [comment]
these queries returns 0 total features. But other queries are oK.  ToT...... May i need your answer..plz

**Comment by elahrvivaz** [comment]
What version of geomesa are you using? Are you running the quickstart or are you using a custom data set? The current geomesa version (2.1) requires hbase 1.3 or 1.4 (see the [installation](https://www.geomesa.org/documentation/user/hbase/install.html#installing-geomesa-hbase-in-geoserver) docs)

**Comment by FjHe** [comment]
i used the newest version of geomesa and run both of quickstart and my custom dataset.

It seems the version question....i'll retry it...

thanks for your reply!!!!!

**Comment by elahrvivaz** [comment]
If this is still an issue, please file a bug in JIRA or start a discussion on the user list or gitter. See https://github.com/locationtech/geomesa#join-the-community
Thanks,
