### ISSUE TITLE
Data Store Tutorials should explain use cases

### ISSUE THREAD

**Issue by sunapi386** [geomesa/geomesa-tutorials#77]
There are several data stores which GeoMesa interface with and there exist [tutorials for each of these](https://www.geomesa.org/documentation/tutorials/index.html#getting-started). 

Namely, these data stores are: 

1. HBase
1. Accumulo
1. Cassandra
1. Kafka
1. FileSystem
1. Kudu
1. Lambda
1. NiFi

Given that there are so many variety of data stores I can use, and as a beginner to this GeoMesa environment, I feel there should be a summary page detailing which one I should follow given my constraints. 

I propose we add a table to the [getting started page](https://www.geomesa.org/documentation/tutorials/index.html#getting-started). For example (examples **may not be correct**): 

| Data Store | Use Case                                                               |
|------------|------------------------------------------------------------------------|
| HBase      | If you're processing data with Apache Spark.                           |
| Accumulo   |                                                                        |
| Cassandra  |                                                                        |
| Kafka      | If you need to queue up a bunch of jobs                                |
| FileSystem | If you want to get off the ground running quickly without any database |
| Kudu       |                                                                        |
| Lambda     | If you are working with AWS Lambda functions?                          |
| NiFi       |                                                                        |

**Comment by elahrvivaz** [comment]
This is a good idea, thanks - I'm going to close this issue, but I've opened a ticket in our bug tracker here: https://geomesa.atlassian.net/browse/GEOMESA-2508

For the moment, if you have any questions about your specific use-case, feel free to ask them in our [gitter channel](https://gitter.im/locationtech/geomesa) or the [user list](https://locationtech.org/mhonarc/lists/geomesa-users/).

In general, most people will already have a database infrastructure in place, so they will use the back-end that matches their environment. If you are concerned about storage costs or setting up a complex environment, then the FileSystem data store is a good place to start, although it generally isn't as performant as a full database back-end. The user interactions with each data store should be very similar, so it is generally possible to start with a simple case (e.g. FileSystem) and then switch to a full-featured back-end with very few code changes.

The Kafka store is different from the other stores, in that it is designed to provide a 'live' view of streaming data, but won't give you the ability to query historical data. Generally you would combine it with one of the persistent back-ends.

Thanks,

Emilio

**Comment by sunapi386** [comment]
Thanks for the explanation. I was looking to narrow down data stores that support spatial indexing/querying and MapReduce capabilities. 

Moving forward, are we expected to create bugs in the Atlassian website?

**Comment by elahrvivaz** [comment]
Yes, tickets against the tutorials themselves can be entered here, but we track tickets against GeoMesa in Jira. If you open an account, you should by default receive permission to create tickets.

All our data stores support spatial indexing and querying, and all except Cassandra support map/reduce (we haven't implemented it for Cassandra since it doesn't usually run alongside hadoop).
