### ISSUE TITLE
geomesa-cassandra-quickstart

### ISSUE THREAD

**Issue by cris7M** [geomesa/geomesa-tutorials#79]
Caused by: com.datastax.driver.core.exceptions.InvalidQueryException: Table names shouldn't be more than 48 characters long (got geo_test_gdelt_2dquickstart_attr_eventcode_geom_dtg_v8")

my table name is geo_test and getting this error with geomesa-tutorials-2.2.0 
and it was working fine with 2.1.1 version.

**Comment by elahrvivaz** [comment]
Thanks for the report. Based on the table name, it looks like you're using 2.3.0-SNAPSHOT, not 2.2.0. I've filed a ticket to fix it for 2.3.0 [here](https://geomesa.atlassian.net/browse/GEOMESA-2589). In the meantime, make sure that you check out the 2.2.1 tag as described in the [documentation](https://www.geomesa.org/documentation/tutorials/index.html#tutorial-versions).
