### ISSUE TITLE
org.locationtech.geomesa:geomesa-z3_2.11:jar:2.3.1

### ISSUE THREAD

**Issue by ShawnXiao105** [geomesa/geomesa-tutorials#80]
2.4 is absolutely failed to run. and I have already checked out the 2.3.x branch. It fails with the following error: 

`Could not resolve dependencies for project org.geomesa.example:geomesa-tutorials-common:jar:2.3.2-SNAPSHOT: Failed to collect dependencies at org.locationtech.geomesa:geomesa-utils_2.11:jar:2.3.1 -> org.locationtech.geomesa:geomesa-z3_2.11:jar:2.3.1 -> org.locationtech.sfcurve:sfcurve-zorder_2.11:jar:0.2.0: Failed to read artifact descriptor for org.locationtech.sfcurve:sfcurve-zorder_2.11:jar:0.2.0: Could not transfer artifact org.locationtech.sfcurve:sfcurve-zorder_2.11:pom:0.2.0 from/to locationtech-releases (https://repo.locationtech.org/content/groups/releases): Connect to repo.locationtech.org:443 [repo.locationtech.org/198.41.30.235] failed: Connection timed out: connect`

![image](https://user-images.githubusercontent.com/1658602/64165864-783a6100-ce78-11e9-8824-62aa7f56f41c.png)

**Comment by ShawnXiao105** [comment]
I have already checked out the 2.3.x branch.

**Comment by elahrvivaz** [comment]
Can you try again? I believe that the locationtech repo was down earlier, but it seems to be back up now.

**Comment by ShawnXiao105** [comment]
> Can you try again? I believe that the locationtech repo was down earlier, but it seems to be back up now.

Thanks, It's OK now.

**Comment by elahrvivaz** [comment]
:+1:
