### ISSUE TITLE
geomesa-hbase python api version too old

### ISSUE THREAD

**Issue by WtyFile** [geomesa/geomesa-tutorials#82]
I use python 3.6.3.Are there any api for python?Our team all use python for development. We will be with problems if there is not python api.

**Comment by elahrvivaz** [comment]
Our main python integration is through [pyspark](https://www.geomesa.org/documentation/user/spark/pyspark.html). This type of question should be directed to our [user list or gitter channel](https://github.com/locationtech/geomesa#join-the-community) - start a discussion there if you have further questions.
Thanks,
